name: dart_console
version: 4.1.1
homepage: https://github.com/onepub-dev/dart_console
description: A helper library for command-line applications that need more control over input/output than the standard library provides.
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  ffi: ^2.1.4
  win32: ^5.12.0
  intl: ^0.20.2
  characters: ^1.4.0
dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
  runtime_common_codestyle:
    git:
      url: https://github.com/open-runtime/runtime_common_codestyle.git
      ref: v0.1.5
platforms:
  linux:
  macos:
  windows:
